spring:
  profiles:
    active: dev
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      default-zone: http://eureka-0.eureka-service.default.svc.cluster.local:8761
logging:
  level:
    org.flywaydb.core: DEBUG